name: cc_rest_api
description: "CC Rest Api is a Dart package that facilitates communication with REST APIs"
version: 1.0.0+1
homepage: https://github.com/codecores/cc_rest_api

environment:
  sdk: '3.4.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true